server:
  port: 8080
spring:
  mvc:
    view:
      suffix: .html
      prefix: /


file:
  upload:
    dir: uploads
  access:
    url: https://backend-187666-8-1362533733.sh.run.tcloudbase.com/uploads